name = "SIMDTypes"
uuid = "94e857df-77ce-4151-89e5-788b33177be4"
authors = ["Julia Computing", "Inc. and Contributors"]
version = "0.1.0"

[deps]
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"

[compat]
Static = "0.1,0.2,0.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
